spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: postgres
    password: 6586
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
server:
  port: 0
  application:
    name: order
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest